set_property PACKAGE_PIN Y18 [get_ports clk_50m]
set_property IOSTANDARD LVCMOS33 [get_ports clk_50m]
create_clock -period 20.000 -name sys_clk [get_ports clk_50m]

set_property PACKAGE_PIN F15 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

# HDMI1
set_property PACKAGE_PIN K4 [get_ports hdmi1_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports hdmi1_clk_p]
set_property PACKAGE_PIN J4 [get_ports hdmi1_clk_n]
set_property IOSTANDARD TMDS_33 [get_ports hdmi1_clk_n]
set_property PACKAGE_PIN L3 [get_ports {hdmi1_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi1_data_p[0]}]
set_property PACKAGE_PIN K3 [get_ports {hdmi1_data_n[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi1_data_n[0]}]
set_property PACKAGE_PIN L5 [get_ports {hdmi1_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi1_data_p[1]}]
set_property PACKAGE_PIN L4 [get_ports {hdmi1_data_n[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi1_data_n[1]}]
set_property PACKAGE_PIN M3 [get_ports {hdmi1_data_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi1_data_p[2]}]
set_property PACKAGE_PIN M2 [get_ports {hdmi1_data_n[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi1_data_n[2]}]
set_property PACKAGE_PIN H5 [get_ports hdmi1_oe]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi1_oe]

# HDMI2
set_property PACKAGE_PIN H4 [get_ports hdmi2_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports hdmi2_clk_p]
set_property PACKAGE_PIN G4 [get_ports hdmi2_clk_n]
set_property IOSTANDARD TMDS_33 [get_ports hdmi2_clk_n]
set_property PACKAGE_PIN E2 [get_ports {hdmi2_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi2_data_p[0]}]
set_property PACKAGE_PIN D2 [get_ports {hdmi2_data_n[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi2_data_n[0]}]
set_property PACKAGE_PIN F3 [get_ports {hdmi2_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi2_data_p[1]}]
set_property PACKAGE_PIN E3 [get_ports {hdmi2_data_n[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi2_data_n[1]}]
set_property PACKAGE_PIN H3 [get_ports {hdmi2_data_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi2_data_p[2]}]
set_property PACKAGE_PIN G3 [get_ports {hdmi2_data_n[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi2_data_n[2]}]
set_property PACKAGE_PIN K2 [get_ports hdmi2_oe]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi2_oe]
