create_clock -name clk -period 20.000 [get_ports clk]
set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN F15 [get_ports rst_n]
set_property PACKAGE_PIN G22 [get_ports {SW[0]}]
set_property PACKAGE_PIN D22 [get_ports {SW[1]}]
set_property PACKAGE_PIN E22 [get_ports {SW[2]}]
set_property PACKAGE_PIN G21 [get_ports {SW[3]}]
set_property PACKAGE_PIN E21 [get_ports {SW[4]}]
set_property PACKAGE_PIN D21 [get_ports {SW[5]}]
set_property PACKAGE_PIN C22 [get_ports {SW[6]}]
set_property PACKAGE_PIN B22 [get_ports {SW[7]}]
set_property PACKAGE_PIN M22 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports led]
